# pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_vqa_capfilt_large.pth'
# pretrained: 'F:/.python/NLP/Compact-BLIP/models/pretrained/model_base_vqa_capfilt_large.pth'
pretrained: 'F:/.python/NLP/Compact-BLIP/output/215925062024.pth'
checkpoint: 'F:/.python/NLP/Compact-BLIP/output/checkpoint_04.pth'

# size of vit model; base or large
vit: 'base'
batch_size_train: 16
batch_size_test: 16
vit_grad_ckpt: False
vit_ckpt_layer: 0
init_lr: 3e-5

image_size: 480

k_test: 128
inference: 'rank'

# optimizer
power_decay: -0.05
weight_decay: 0.05
min_lr: 0
max_epoch: 10